In [1]:
import numpy as np
def softmax(x):
    exp_a = np.exp(x)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y


In [2]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
exp_a


array([ 1.34985881, 18.17414537, 54.59815003])

In [4]:
sum_exp_a = np.sum(exp_a)
sum_exp_a


74.1221542101633

In [5]:
y = exp_a / sum_exp_a
y


array([0.01821127, 0.24519181, 0.73659691])

In [7]:
sum_y = np.sum(y)
sum_y


1.0

In [8]:
print(softmax(a))


[0.01821127 0.24519181 0.73659691]


구현이 잘 되지만 e의 지수를 포함해서 지수함수가 커지면 큰 폭으로 증가함.
exp(1) = 20,000, exp(10) = 0이 40개가 넘음, exp(1000) = inf


In [14]:
a = np.array([1010, 1000, 990])
print(np.exp(a) / np.sum(np.exp(a)))


[nan nan nan]


/tmp/ipykernel_1685429/5665391.py:2: RuntimeWarning: overflow encountered in exp
  print(np.exp(a) / np.sum(np.exp(a)))
/tmp/ipykernel_1685429/5665391.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.exp(a) / np.sum(np.exp(a)))


In [17]:
c = np.max(a)
c


1010

In [18]:
print(a-c)


[  0 -10 -20]


In [19]:
def new_softmax(x):
    c = np.max(x) # 최대값
    exp_a = np.exp(a-c) # 각 원소에 최댓값을 뺀 값에 exp를 취함 - overflow 방지 
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y


In [21]:
print(new_softmax(a))
print(np.sum(new_softmax(a)))


[9.99954600e-01 4.53978686e-05 2.06106005e-09]
1.0
